---
dependencies: []

galaxy_info:
  role_name: Symfony
  author: Moncif EL KASSIMI
  description: Deploy a symfony webapp
  company: "Moncif EL KASSIMI"
  license: "test Moncif EL KASSIMI"
  min_ansible_version: 2.4
  platforms:
    - name: GenericUNIX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - packaging
    - web