---
  - name: "Create {{user_group}} group"
    group:
      name: "{{ user_group }}"
      state: present

  - name: "Create {{install_user}} user"
    user:
      name: "{{install_user}}"
      group: "{{user_group}}"
      
  - name: "Prepare installing PHP8.0"
    ansible.builtin.apt_repository:
      repo: ppa:ondrej/php

  - name: "Prepare install Symphony CLI"
    shell: echo 'deb [trusted=yes] https://repo.symfony.com/apt/ /' | sudo tee /etc/apt/sources.list.d/symfony-cli.list
    changed_when: false

  - name: "Install required packages"
    apt: name={{ item }}  update_cache=yes state=latest
    with_items:
      - nginx 
      - software-properties-common
      - php8.0
      - php8.0-sqlite3   
      - symfony-cli   
      - net-tools
      - tree
      - php8.0-xml
      - php8.0-mbstring
      - php8.0-fpm
      - php8.0-zip
    no_log: yes  
   
  - name: "Git checkout"
    git:
      repo: "https://github.com/symfony/demo.git" 
      dest: "{{install_path}}/test_quable/"
      version: "{{git_branch}}"
      update: yes
      force: yes
    no_log: yes  

  - name: "Change ownership of web project"
    file:
      path: "{{install_path}}/test_quable/"
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

  - name: "Configure Nginx"
    include_tasks: configure_nginx.yml 

  - name: "Configure Symfony"
    include_tasks: configure_symfony.yml




 

       

    